# Generated by Django 4.0.1 on 2022-01-18 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySellingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('opening_command', models.CharField(blank=True, max_length=255, null=True)),
                ('ending_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('ending_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='medicinecheckout',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicinecheckout',
            name='status',
            field=models.CharField(blank=True, choices=[('PROCESSING', 'PROCESSING'), ('DONE', 'DONE')], max_length=255, null=True),
        ),
    ]
