# Generated by Django 3.2.9 on 2021-12-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='show_vat',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='is_out_of_stock',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='is_active',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('CLOSED', 'CLOSED')], max_length=255, null=True),
        ),
    ]
