# Generated by Django 4.0.1 on 2022-01-18 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0002_dailysellingsession_medicinecheckout_is_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField()),
                ('is_seen', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
