# Generated by Django 3.2 on 2022-01-01 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0003_auto_20220101_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacyapp.shop'),
        ),
    ]
