# Generated by Django 4.0.1 on 2022-01-18 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0003_notificationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationmodel',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pharmacyapp.shop'),
        ),
    ]
