# Generated by Django 4.0.1 on 2022-01-23 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0006_alter_medicinebrand_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='med_power',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacyapp.medicinepower'),
        ),
    ]
