# Generated by Django 4.0.1 on 2022-01-23 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0007_alter_medicine_med_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='med_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacyapp.vendor'),
        ),
    ]
