# Generated by Django 4.0.1 on 2022-01-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0010_medicinecheckout_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinecheckout',
            name='quantity',
        ),
    ]
